# Form implementation generated from reading ui file '/home/fiejtek_1162023/MealGambler/Ui_Files/EditMealDialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(parent=Dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameLineEdit)
        self.categoryLabel = QtWidgets.QLabel(parent=Dialog)
        self.categoryLabel.setObjectName("categoryLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.categoryLabel)
        self.categoryComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.categoryComboBox)
        self.caloriesLabel = QtWidgets.QLabel(parent=Dialog)
        self.caloriesLabel.setObjectName("caloriesLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.caloriesLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.caloriesSpinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.caloriesSpinBox.setObjectName("caloriesSpinBox")
        self.horizontalLayout.addWidget(self.caloriesSpinBox)
        self.kcalLabel = QtWidgets.QLabel(parent=Dialog)
        self.kcalLabel.setObjectName("kcalLabel")
        self.horizontalLayout.addWidget(self.kcalLabel)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout)
        self.ingredientsLabel = QtWidgets.QLabel(parent=Dialog)
        self.ingredientsLabel.setObjectName("ingredientsLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ingredientsLabel)
        self.ingredientsPlainTextEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.ingredientsPlainTextEdit.setObjectName("ingredientsPlainTextEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ingredientsPlainTextEdit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.nameLabel.setText(_translate("Dialog", "Name"))
        self.categoryLabel.setText(_translate("Dialog", "Category"))
        self.categoryComboBox.setItemText(0, _translate("Dialog", "Other"))
        self.categoryComboBox.setItemText(1, _translate("Dialog", "Breakfast"))
        self.categoryComboBox.setItemText(2, _translate("Dialog", "Dinner"))
        self.categoryComboBox.setItemText(3, _translate("Dialog", "Supper"))
        self.categoryComboBox.setItemText(4, _translate("Dialog", "Snack"))
        self.caloriesLabel.setText(_translate("Dialog", "Calories"))
        self.kcalLabel.setText(_translate("Dialog", "kcal"))
        self.ingredientsLabel.setText(_translate("Dialog", "Ingredients"))
