# Form implementation generated from reading ui file '/home/fiejtek_1162023/MealGambler/Ui_Files/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(263, 149)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.editMealsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.editMealsButton.setObjectName("editMealsButton")
        self.gridLayout.addWidget(self.editMealsButton, 2, 0, 1, 1)
        self.generateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.generateButton.setObjectName("generateButton")
        self.gridLayout.addWidget(self.generateButton, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.generateButton, self.editMealsButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.editMealsButton.setText(_translate("MainWindow", "Edit meals"))
        self.generateButton.setText(_translate("MainWindow", "Generate meal plan"))
        self.pushButton.setText(_translate("MainWindow", "Exit"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
